"""Description of changes

Revision ID: d978c6e71cc2
Revises: 
Create Date: 2024-03-06 01:48:43.851790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd978c6e71cc2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userInfo')
    op.add_column('todo', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'todo', 'user_info', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todo', type_='foreignkey')
    op.drop_column('todo', 'user_id')
    op.create_table('userInfo',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"userInfo_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='userInfo_pkey'),
    sa.UniqueConstraint('email', name='userInfo_email_key'),
    sa.UniqueConstraint('username', name='userInfo_username_key')
    )
    # ### end Alembic commands ###
