"""set TodoUser, Todo one-to-many relationship

Revision ID: 033e0b9cf2f1
Revises: e8e20c8db618
Create Date: 2024-03-07 23:18:16.402220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '033e0b9cf2f1'
down_revision = 'e8e20c8db618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'todo_user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
