"""Fixed Todo model

Revision ID: 1ef75345333b
Revises: c06d6abd0197
Create Date: 2024-03-01 12:46:37.429728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ef75345333b'
down_revision = 'c06d6abd0197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('todo_description_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.create_unique_constraint('todo_description_key', ['description'])
        batch_op.drop_column('id')

    # ### end Alembic commands ###
