"""TodoUser table add

Revision ID: 951766782206
Revises: fc71c04902a9
Create Date: 2024-03-07 17:56:01.837614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951766782206'
down_revision = 'fc71c04902a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userInfo')
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.alter_column('task',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.alter_column('task',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    op.create_table('userInfo',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"userInfo_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='userInfo_pkey'),
    sa.UniqueConstraint('email', name='userInfo_email_key'),
    sa.UniqueConstraint('username', name='userInfo_username_key')
    )
    # ### end Alembic commands ###
