"""change password_hash string max length, add new table

Revision ID: c06d6abd0197
Revises: e79dbe08f5be
Create Date: 2024-03-01 12:43:35.168033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c06d6abd0197'
down_revision = 'e79dbe08f5be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('task', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=15), nullable=True),
    sa.Column('importance', sa.String(length=40), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time', sa.Time(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('task'),
    sa.UniqueConstraint('description')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo')
    # ### end Alembic commands ###
