"""change Todo table setting

Revision ID: f38f76507819
Revises: 1ef75345333b
Create Date: 2024-03-01 12:51:19.238823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f38f76507819'
down_revision = '1ef75345333b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.alter_column('task',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=200),
               nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=15),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('importance',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.alter_column('importance',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=40),
               existing_nullable=True)
        batch_op.alter_column('description',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=15),
               existing_nullable=True)
        batch_op.alter_column('task',
               existing_type=sa.String(length=200),
               type_=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
