"""TodoUser table add

Revision ID: fc71c04902a9
Revises: f38f76507819
Create Date: 2024-03-07 17:54:36.272989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc71c04902a9'
down_revision = 'f38f76507819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('userInfo')
    op.drop_table('user_info')
    op.drop_table('blog_posts')
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.alter_column('task',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.alter_column('task',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    op.create_table('blog_posts',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('blog_posts_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('subtitle', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('date', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('img_url', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user_info.id'], name='blog_posts_author_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='blog_posts_pkey'),
    sa.UniqueConstraint('title', name='blog_posts_title_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_info',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_info_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_info_pkey'),
    sa.UniqueConstraint('email', name='user_info_email_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('userInfo',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"userInfo_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='userInfo_pkey'),
    sa.UniqueConstraint('email', name='userInfo_email_key'),
    sa.UniqueConstraint('username', name='userInfo_username_key')
    )
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('text', sa.VARCHAR(length=300), autoincrement=False, nullable=False),
    sa.Column('blogpost_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['blogpost_id'], ['blog_posts.id'], name='comments_blogpost_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='comments_pkey')
    )
    # ### end Alembic commands ###
